
// This file has been generated by the GUI designer. Do not modify.
namespace CraftalystLauncher
{
	public partial class InstallationDialog
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label titleLabel;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView log;
		private global::Gtk.Label status;
		private global::Gtk.ProgressBar progress;
		private global::Gtk.Button buttonCancel;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CraftalystLauncher.InstallationDialog
			this.Name = "CraftalystLauncher.InstallationDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child CraftalystLauncher.InstallationDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.titleLabel = new global::Gtk.Label ();
			this.titleLabel.Name = "titleLabel";
			this.titleLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Installing Minecraft...");
			this.vbox2.Add (this.titleLabel);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.titleLabel]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.log = new global::Gtk.TextView ();
			this.log.CanFocus = true;
			this.log.Name = "log";
			this.log.Editable = false;
			this.log.CursorVisible = false;
			this.GtkScrolledWindow.Add (this.log);
			this.vbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
			w4.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.status = new global::Gtk.Label ();
			this.status.Name = "status";
			this.status.LabelProp = global::Mono.Unix.Catalog.GetString ("Please wait...");
			this.vbox2.Add (this.status);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.status]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.progress = new global::Gtk.ProgressBar ();
			this.progress.Name = "progress";
			this.vbox2.Add (this.progress);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.progress]));
			w6.Position = 3;
			w6.Expand = false;
			w6.Fill = false;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox2]));
			w7.Position = 0;
			// Internal child CraftalystLauncher.InstallationDialog.ActionArea
			global::Gtk.HButtonBox w8 = this.ActionArea;
			w8.Name = "dialog1_ActionArea";
			w8.Spacing = 10;
			w8.BorderWidth = ((uint)(5));
			w8.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w8 [this.buttonCancel]));
			w9.Expand = false;
			w9.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 810;
			this.DefaultHeight = 437;
			this.Show ();
			this.buttonCancel.Activated += new global::System.EventHandler (this.OnButtonCancelActivated);
			this.buttonCancel.Clicked += new global::System.EventHandler (this.OnButtonCancelActivated);
		}
	}
}
