
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.VBox vbox1;
	private global::Gtk.HPaned hpaned1;
	private global::Gtk.VBox vbox4;
	private global::Gtk.HBox hbox4;
	private global::Gtk.Image image1;
	private global::Gtk.Label titleLabel;
	private global::Gtk.Label label2;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView minecraftLog;
	private global::Gtk.VBox vbox3;
	private global::Gtk.Label usernameLabel;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.TextView overviewAndStatus;
	private global::Gtk.Label label1;
	private global::Gtk.ScrolledWindow GtkScrolledWindow2;
	private global::Gtk.TextView serverNews;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Button playButton;
	private global::Gtk.Button tsButton;
	private global::Gtk.Button mapButton;
	private global::Gtk.Button wikiButton;
	private global::Gtk.Button forumsButton;
	private global::Gtk.Button websiteButton;
	private global::Gtk.Button donateButton;
	private global::Gtk.Button reportServerDownButton;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		this.vbox1.BorderWidth = ((uint)(5));
		// Container child vbox1.Gtk.Box+BoxChild
		this.hpaned1 = new global::Gtk.HPaned ();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 607;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.image1 = new global::Gtk.Image ();
		this.image1.Name = "image1";
		this.image1.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./tirrin_test_favicon1.png"));
		this.hbox4.Add (this.image1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.image1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		w2.Padding = ((uint)(10));
		// Container child hbox4.Gtk.Box+BoxChild
		this.titleLabel = new global::Gtk.Label ();
		this.titleLabel.Name = "titleLabel";
		this.titleLabel.LabelProp = "<big><big><big><big>Tirrin</big></big></big></big>";
		this.titleLabel.UseMarkup = true;
		this.hbox4.Add (this.titleLabel);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.titleLabel]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		this.vbox4.Add (this.hbox4);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox4]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.Xalign = 0F;
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Minecraft:");
		this.vbox4.Add (this.label2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label2]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.minecraftLog = new global::Gtk.TextView ();
		this.minecraftLog.Buffer.Text = "Click Play below to start Minecraft!";
		this.minecraftLog.CanFocus = true;
		this.minecraftLog.Name = "minecraftLog";
		this.GtkScrolledWindow.Add (this.minecraftLog);
		this.vbox4.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow]));
		w7.Position = 2;
		this.hpaned1.Add (this.vbox4);
		global::Gtk.Paned.PanedChild w8 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.vbox4]));
		w8.Resize = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.usernameLabel = new global::Gtk.Label ();
		this.usernameLabel.Name = "usernameLabel";
		this.usernameLabel.Xalign = 1F;
		this.usernameLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Playing as <b>rezonaut</b>");
		this.usernameLabel.UseMarkup = true;
		this.vbox3.Add (this.usernameLabel);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.usernameLabel]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.overviewAndStatus = new global::Gtk.TextView ();
		this.overviewAndStatus.Buffer.Text = "Please wait...";
		this.overviewAndStatus.CanFocus = true;
		this.overviewAndStatus.Name = "overviewAndStatus";
		this.GtkScrolledWindow1.Add (this.overviewAndStatus);
		this.vbox3.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow1]));
		w11.Position = 1;
		// Container child vbox3.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("News / Message of the Day");
		this.vbox3.Add (this.label1);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label1]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.serverNews = new global::Gtk.TextView ();
		this.serverNews.Buffer.Text = "Things and news and things!";
		this.serverNews.CanFocus = true;
		this.serverNews.Name = "serverNews";
		this.GtkScrolledWindow2.Add (this.serverNews);
		this.vbox3.Add (this.GtkScrolledWindow2);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow2]));
		w14.Position = 3;
		this.hpaned1.Add (this.vbox3);
		this.vbox1.Add (this.hpaned1);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hpaned1]));
		w16.Position = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.playButton = new global::Gtk.Button ();
		this.playButton.CanFocus = true;
		this.playButton.Name = "playButton";
		this.playButton.UseUnderline = true;
		this.playButton.Label = global::Mono.Unix.Catalog.GetString ("Play");
		this.hbox2.Add (this.playButton);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.playButton]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.tsButton = new global::Gtk.Button ();
		this.tsButton.CanFocus = true;
		this.tsButton.Name = "tsButton";
		this.tsButton.UseUnderline = true;
		this.tsButton.Label = global::Mono.Unix.Catalog.GetString ("Teamspeak");
		this.hbox2.Add (this.tsButton);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.tsButton]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.mapButton = new global::Gtk.Button ();
		this.mapButton.CanFocus = true;
		this.mapButton.Name = "mapButton";
		this.mapButton.UseUnderline = true;
		this.mapButton.Label = global::Mono.Unix.Catalog.GetString ("Map");
		this.hbox2.Add (this.mapButton);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.mapButton]));
		w19.Position = 2;
		w19.Expand = false;
		w19.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.wikiButton = new global::Gtk.Button ();
		this.wikiButton.CanFocus = true;
		this.wikiButton.Name = "wikiButton";
		this.wikiButton.UseUnderline = true;
		this.wikiButton.Label = global::Mono.Unix.Catalog.GetString ("Wiki");
		this.hbox2.Add (this.wikiButton);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.wikiButton]));
		w20.Position = 3;
		w20.Expand = false;
		w20.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.forumsButton = new global::Gtk.Button ();
		this.forumsButton.CanFocus = true;
		this.forumsButton.Name = "forumsButton";
		this.forumsButton.UseUnderline = true;
		this.forumsButton.Label = global::Mono.Unix.Catalog.GetString ("Forums");
		this.hbox2.Add (this.forumsButton);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.forumsButton]));
		w21.Position = 4;
		w21.Expand = false;
		w21.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.websiteButton = new global::Gtk.Button ();
		this.websiteButton.CanFocus = true;
		this.websiteButton.Name = "websiteButton";
		this.websiteButton.UseUnderline = true;
		this.websiteButton.Label = global::Mono.Unix.Catalog.GetString ("Website");
		this.hbox2.Add (this.websiteButton);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.websiteButton]));
		w22.Position = 5;
		w22.Expand = false;
		w22.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.donateButton = new global::Gtk.Button ();
		this.donateButton.CanFocus = true;
		this.donateButton.Name = "donateButton";
		this.donateButton.UseUnderline = true;
		this.donateButton.Label = global::Mono.Unix.Catalog.GetString ("Donate");
		this.hbox2.Add (this.donateButton);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.donateButton]));
		w23.Position = 6;
		w23.Expand = false;
		w23.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.reportServerDownButton = new global::Gtk.Button ();
		this.reportServerDownButton.CanFocus = true;
		this.reportServerDownButton.Name = "reportServerDownButton";
		this.reportServerDownButton.UseUnderline = true;
		this.reportServerDownButton.Label = global::Mono.Unix.Catalog.GetString ("Report Server Down");
		this.hbox2.Add (this.reportServerDownButton);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.reportServerDownButton]));
		w24.Position = 7;
		w24.Expand = false;
		w24.Fill = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w25.Position = 1;
		w25.Expand = false;
		w25.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 1139;
		this.DefaultHeight = 566;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.playButton.Activated += new global::System.EventHandler (this.OnPlayButtonActivated);
		this.playButton.Clicked += new global::System.EventHandler (this.OnPlayButtonActivated);
		this.tsButton.Activated += new global::System.EventHandler (this.OnTsButtonActivated);
		this.tsButton.Clicked += new global::System.EventHandler (this.OnTsButtonActivated);
		this.mapButton.Activated += new global::System.EventHandler (this.OnMapButtonActivated);
		this.mapButton.Clicked += new global::System.EventHandler (this.OnMapButtonActivated);
		this.wikiButton.Activated += new global::System.EventHandler (this.OnWikiButtonActivated);
		this.wikiButton.Clicked += new global::System.EventHandler (this.OnWikiButtonActivated);
		this.forumsButton.Activated += new global::System.EventHandler (this.OnForumsButtonActivated);
		this.forumsButton.Clicked += new global::System.EventHandler (this.OnForumsButtonActivated);
		this.websiteButton.Activated += new global::System.EventHandler (this.OnWebsiteButtonActivated);
		this.websiteButton.Clicked += new global::System.EventHandler (this.OnWebsiteButtonActivated);
		this.donateButton.Activated += new global::System.EventHandler (this.OnDonateButtonActivated);
		this.donateButton.Clicked += new global::System.EventHandler (this.OnDonateButtonActivated);
		this.reportServerDownButton.Activated += new global::System.EventHandler (this.OnReportServerDownButtonActivated);
		this.reportServerDownButton.Clicked += new global::System.EventHandler (this.OnReportServerDownButtonActivated);
	}
}
